openapi: 3.0.0
info:
  title: Category API
  version: 1.0.0
  description: API Category

paths:
  /category:
    get:
      summary: Obtener todas las categorías
      responses:
        '200':
          description: Lista de categorías
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Crear una nueva categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Categoría creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

  /category/{categoryId}:
    parameters:
      - in: path
        name: categoryId
        required: true
        schema:
          type: string
        description: ID de la categoría
    get:
      summary: Obtener una categoría por ID
      responses:
        '200':
          description: Categoría encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Categoría no encontrada
    put:
      summary: Actualizar una categoría por ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: Categoría actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Categoría no encontrada
    delete:
      summary: Eliminar una categoría por ID
      responses:
        '204':
          description: Categoría eliminada exitosamente
        '404':
          description: Categoría no encontrada
  

components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
        icon:
          type: string
        color:
          type: string
      required:
        - name
    
